FROM node:22-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm@10.23.0
COPY . .
RUN pnpm install && pnpm build

FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=builder /app /app
ENV NODE_ENV=production
CMD ["node", "services/simulator/dist/standalone.js"]
